remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.
theme: jekyll-theme-hacker

title: "Intergalactic Unknown"
description: "User will embark on a intergalactic choice based journey, forcing them to manage their supplies while balancing decision making."
author:
  name: "Jonathan Rodrigues"

# Do not change the following line.
  copyright: true
