remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Intergalactic Unknown"
description: "User embarks on a intergalactic choice based journey, forcing them to manage their supplies while balancing decision making."
author:
  name: "Jonathan Rodrigues"

# Do not change the following line.
  copyright: true
